### ISSUE TITLE
食事制限

### ISSUE THREAD

**Issue by messcat-38** [ekuinox/rules#1]
絶対に大盛りを注文しない
揚げ物を食べない
間食を完全にやめる

**Comment by ekuinox** [comment]
大盛りに関しては取り入れていけると思う
揚げ物に関しては救済措置がほしい
間食を完全にやめるも取り入れられる

**Comment by ekuinox** [comment]
https://github.com/ekuinox/rules/commit/2e8f57bd46e2fe2bb6f3779ee8bda92003ae3f8f 大盛りをやめます
